### ISSUE TITLE
Autoreconnect still active after explicit call to close the WebSocket

### ISSUE THREAD

**Issue by kroepr** [shannah/cn1-websockets#14]
If autoReconnect is set and you close the WebSocket it will still continue to try and reconnect.

I tried setting autoReconnect to 0 before the call to close() however based on the code it seems like the reconnectTimer is never reset when turning off autoReconnect.

**Comment by shannah** [comment]
What platform?  How are you closing the connection.  It should only try to reconnect if it closes with an error code (ie not a normal closing)

**Comment by kroepr** [comment]
I agree. However that is not happening. When closing the connection using the regular close() method it still tries to reconnect. This is happening in both the simulator and the Android environment.

Based on the source code it makes sense since the reconnectTimer and the reconnectTimerThread never get reset after calling autoReconnect(0)

**Comment by shannah** [comment]
I'm tied up at the moment on other issues, but should be able to fix this within the next 2 weeks.

**Comment by kroepr** [comment]
Thank you for the update.

**Comment by kroepr** [comment]
Do you have an update on this issue?

**Comment by kroepr** [comment]
Could I please get an update on this issue?

**Comment by shannah** [comment]
Haven’t had a chance to get to it yet.  I spent some time last week trying to reproduce the issue but wasn’t successful.  I.e. i couldn’t get it to fail

**Comment by kroepr** [comment]
I will try to put some simple sample code together that shows the issue.

**Comment by kroepr** [comment]
`package com.cn1test;

import com.codename1.io.Log;
import com.codename1.io.websocket.WebSocket;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import java.util.Timer;
import java.util.TimerTask;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication
{
    private Form current;
    private Resources theme;
    private EventSocket client;
    
    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));
        hi.show();

        client = new EventSocket("ws://localhost:4442");
        client.autoReconnect(10000);
        client.connect();
        
        Timer timer = new Timer();
        timer.schedule(new TimerTask()
        {
            public void run()
            {
                try
                {
                    client.autoReconnect(0);
                    client.close();
                    client = new EventSocket("ws://localhost:4442");

                    client.autoReconnect(10000);
                    client.connect();
                }
                catch (Exception e)
                {
                    e.printStackTrace();
                }
            }
        }, 30000);
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }


    public static class EventSocket extends WebSocket
    {
        String url;
        
        public EventSocket(String url)
        {
            super(url);
            this.url = url;
        }

        @Override
        public void onOpen()
        {
        }

        @Override
        public void onClose(int statusCode, String reason)
        {
        }

        @Override
        public void onError(Exception throwable)
        {
        }

        @Override
        public void onMessage(final String message)
        {
        }
        
        @Override
        public void onMessage(byte[] message)
        {
        }
    }
}
`

**Comment by kroepr** [comment]
`package com.cn1test;

import com.codename1.io.Log;
import com.codename1.io.websocket.WebSocket;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import java.util.Timer;
import java.util.TimerTask;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication
{
    private Form current;
    private Resources theme;
    private EventSocket client;
    
    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));
        hi.show();

        client = new EventSocket("ws://localhost:4442");
        client.autoReconnect(10000);
        client.connect();
        
        Timer timer = new Timer();
        timer.schedule(new TimerTask()
        {
            public void run()
            {
                try
                {
                    client.autoReconnect(0);
                    client.close();
                    client = new EventSocket("ws://localhost:4442");

                    client.autoReconnect(10000);
                    client.connect();
                }
                catch (Exception e)
                {
                    e.printStackTrace();
                }
            }
        }, 30000);
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }


    public static class EventSocket extends WebSocket
    {
        String url;
        
        public EventSocket(String url)
        {
            super(url);
            this.url = url;
        }

        @Override
        public void onOpen()
        {
        }

        @Override
        public void onClose(int statusCode, String reason)
        {
        }

        @Override
        public void onError(Exception throwable)
        {
        }

        @Override
        public void onMessage(final String message)
        {
        }
        
        @Override
        public void onMessage(byte[] message)
        {
        }
    }
}
`

**Comment by kroepr** [comment]
```
package com.cn1test;

import com.codename1.io.Log;
import com.codename1.io.websocket.WebSocket;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import java.util.Timer;
import java.util.TimerTask;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication
{
    private Form current;
    private Resources theme;
    private EventSocket client;
    
    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));
        hi.show();

        client = new EventSocket("ws://localhost:4442");
        client.autoReconnect(10000);
        client.connect();
        
        Timer timer = new Timer();
        timer.schedule(new TimerTask()
        {
            public void run()
            {
                try
                {
                    client.autoReconnect(0);
                    client.close();
                    client = new EventSocket("ws://localhost:4442");

                    client.autoReconnect(10000);
                    client.connect();
                }
                catch (Exception e)
                {
                    e.printStackTrace();
                }
            }
        }, 30000);
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }


    public static class EventSocket extends WebSocket
    {
        String url;
        
        public EventSocket(String url)
        {
            super(url);
            this.url = url;
        }

        @Override
        public void onOpen()
        {
        }

        @Override
        public void onClose(int statusCode, String reason)
        {
        }

        @Override
        public void onError(Exception throwable)
        {
        }

        @Override
        public void onMessage(final String message)
        {
        }
        
        @Override
        public void onMessage(byte[] message)
        {
        }
    }
}

```

**Comment by kroepr** [comment]
The code above will reproduce the bug. 

Make sure there is no websocket server on port 4442 on the localhost.

When you run this you will see "Attempting to reconnect..." in the logs 3 times before the timer goes off. Then the original WebSocket is closed and a new one is opened. After that you will see "Attempting to reconnect..." twice for the original and the new one.

This is the bug. The original connection was somehow never closed.

**Comment by shannah** [comment]
This is fixed now.  It will be available soon in codename One settings.  Or you can download directly from Github (1.3.2 release)

**Comment by kroepr** [comment]
Thank you.
