### ISSUE TITLE
[BUG] `autoreconnect` implementation is wrong

### ISSUE THREAD

**Issue by jsfan3** [shannah/cn1-websockets#16]
First of all, the following bug can be reproduced on Android and Simulator only. On iOS the `autoreconnect` doesn't work at all: if you turn off the Internet connection and then turn on it again, the WebSocket connection is not reopened on iOS, but on Android only. However, Android and Simulator have another issue, as described below.

For your convenience, to test my client code and to reproduce the bug, I keep my testing Spring Boot server (`chat.mydissent.net`) running for some days. On the server-side, there is a timer that send a WebSocket text message every second to the client with id "1234". It's only a test, I mostly copied that server code from the Codename One Academy, so I assume that it's correct. 

Please try the following client code:
```
        String uniqueId = "1234";
        Form hi = new Form("WebSocket Test", BoxLayout.y());
        hi.show();

        final WebSocket sock = new WebSocket("wss://chat.mydissent.net/wsMsg") {
            @Override
            protected void onOpen() {
                Log.p("WebSocket onOpen - Sending uniqueId: " + uniqueId);
                hi.add("WebSocket onOpen - Sending uniqueId: " + uniqueId);
                hi.animateLayout(400);
                send(uniqueId);
            }

            @Override
            protected void onClose(int statusCode, String reason) {
                Log.p("WebSocket onClose");
                hi.add("WebSocket onClose");
                hi.animateLayout(400);
            }

            @Override
            protected void onMessage(String message) {
                Log.p("WebSocket onMessage: " + message);
                hi.add(new SpanLabel("WebSocket onMessage: " + message));
                hi.animateLayout(400);
            }

            @Override
            protected void onMessage(byte[] message) {
                Log.p("WebSocket onMessage (byte[]): " + message.toString());
            }

            @Override
            protected void onError(Exception ex) {
                Log.e(ex);
                hi.add(new SpanLabel("WebSocket onError:\n" + ex.getMessage()));
            }
        };
        sock.connect();
        sock.autoReconnect(5000);
        
        UITimer.timer(5000, false, hi, () -> {
            sock.close();
        });
```

The output is:

![WebSocket](https://user-images.githubusercontent.com/1997316/81817857-8c694e80-952d-11ea-9bd5-c9fa99f5db02.png)

As you can see, after closing the WebSocket connection, `autoReconnect` reopened it. The expected behavior is that autoReconnect must reconnect only on network errors, and not when close is explicitly invoked.
The other excepted behaviour is that after turning off and then turning on the Internet connection,  `autoReconnect` must work, but it's not so on iOS.

**Comment by jsfan3** [comment]
If you need, I can give you a link to download the Netbeans projects (client and server) of the test case.

**Comment by jsfan3** [comment]
ChatApp (Codename One) and ChatServer (Spring Boot) Netbeans Projects, with minimal code, only to test this bug report:
https://www.informatica-libera.net/docLavoro/TestWebSocket.zip

**Comment by shannah** [comment]
Both of these issues are fixed now.  Update to the latest at https://github.com/shannah/cn1-websockets/tree/master/dist

This will be in CodenameOne settings in the next update.
