### ISSUE TITLE
[BUG] reconnect issue on iOS

### ISSUE THREAD

**Issue by jsfan3** [shannah/cn1-websockets#17]
Thank you for your last fixes, now the `autoreconnect` works as required :)

But there is still an issue on iOS regarding the `reconnect`.
Please try this test case, as it is, on iOS:
https://gist.github.com/jsfan3/66089940cbb7a6b28e3ac12e522e13ad

Then try to move the app from foreground to background and vice versa several times: at some point, the websocket connection is not reconnected.

**Comment by shannah** [comment]
When you call socket.close() in stop() it cancels the auto reconnection.

**Comment by jsfan3** [comment]
You're right! :)
You did very good fixes: I tested the cn1lib on a pretty unstable connection and it works great :)

Fixed so:
```
public void start() {
        if (sock != null) {
            sock.reconnect();
            sock.autoReconnect(5000);
        }
        [...]
```
