### ISSUE TITLE
Working with audio

### ISSUE THREAD

**Issue by schreiby** [shannah/cn1-websockets#18]
I saw that you can send and receive data as `byte[]` -- would this be a good fit for working with audio to act as push-to-talk? I realize that there would be an issue with background services. 

Would you recommend this for such a use case? Would it be too slow to process the audio? 

Any related advice or pointers would be appreciated. 

Thank you.

**Comment by shannah** [comment]
Audio should be fine.  I have seen other projects passing audio over websockets without issue.

**Comment by schreiby** [comment]
Thank you.
