### ISSUE TITLE
close() method impl on Android noop

### ISSUE THREAD

**Issue by twhayden** [shannah/cn1-websockets#4]
The close() method on the WebSocket seemed to do nothing (at least on Android). 

When looking at the code, its actual implementation seems to be commented out.  So right now there is no way to disconnect from a server unless the server itself disconnects you.

**Comment by shannah** [comment]
That is likely an omission.  Can you try changing that commented out client.close() to client.sendClose()
https://github.com/shannah/cn1-websockets/blob/master/cn1-websockets-demo/native/android/com/codename1/io/websocket/WebSocketNativeImplImpl.java#L42

And try building from source.   See if that fixes it for you?  If it works.  Let me know and I'll commit it.

**Comment by tmancini** [comment]
Did anything ever happen with this?  When running the simulator sock.getReadyState() returns OPEN both before and after calling close() on the socket.

**Comment by shannah** [comment]
This is now fixed in the latest release.
