### ISSUE TITLE
Simulator no longer connecting to WebSocket?

### ISSUE THREAD

**Issue by tmancini** [shannah/cn1-websockets#5]
A few weeks ago I downloaded a zip of the demo.  I modified the code to point to a local running WebSocket and had a chat working back and forth from an iOS debug build on my iPhone along with Javascript in a web browser. After updating my Codename One Eclipse plug-in, I am no longer able to connect to the WebSocket. The WebSocket itself appears to be perfectly fine since everything from the browser still works.

The sock.connect() call in the init() method of my Codename One project does not seem to be connecting properly. I am not entirely sure how to debug this native method. Is there anything I can try or possibly something that was changed that might caused this to stop working?

I even tried changing SERVER_URL to ws://translation.weblite.ca:8080/WebSocketDemo/chat, but it does not seem to be able to connect to that either anymore. All recent testing has been done using the Simulator.

**Comment by shannah** [comment]
Strange.  Have you disabled the network in the simulator? "Simulate" > "Network" > "Disconnected" ?

**Comment by tmancini** [comment]
Network is definitely set to connected.  I am going to try and get it on my phone in debug mode to test it out there.

**Comment by shannah** [comment]
Is this problem only in the simulator?  Can you share a test case?

**Comment by tmancini** [comment]
This is what my WebSocketDemo looks like right now.  Does not seem to be working in Simulator or on iPhone with a Debug build.

`import java.io.IOException;
import com.codename1.components.SpanLabel;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Container;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.TextField;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

public class WebSocketDemo {

  private Form current;
  private Resources theme;
  WebSocket sock;
  Container chatContainer;

  public static final String SERVER_URL = "ws://translation.weblite.ca:8080/WebSocketDemo/chat";
// public static final String SERVER_URL = "ws://192.168.1.2:8080/WebSocketUpload/chat";

  public void init(Object context) {
    try {
      theme = Resources.openLayered("/theme");
      UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
    }
    catch(IOException e) {
      e.printStackTrace();
    }
    // Pro users - uncomment this code to get crash reports sent to you automatically
    /*
     * Display.getInstance().addEdtErrorHandler(new ActionListener() {
     * public void actionPerformed(ActionEvent evt) {
     * evt.consume();
     * Log.p("Exception in AppName version " + Display.getInstance().getProperty("AppVersion", "Unknown"));
     * Log.p("OS " + Display.getInstance().getPlatformName());
     * Log.p("Error " + evt.getSource());
     * Log.p("Current Form " + Display.getInstance().getCurrent().getName());
     * Log.e((Throwable)evt.getSource());
     * Log.sendLog();
     * }
     * });
     */

    sock = new WebSocket(SERVER_URL) {

      @Override
      protected void onOpen() {
        System.out.println("In onOpen");
      }

      @Override
      protected void onClose(int statusCode, String reason) {

      }

      @Override
      protected void onMessage(final String message) {
        System.out.println("Received message " + message);
        Display.getInstance().callSerially(new Runnable() {

          public void run() {
            if(chatContainer == null) {
              return;
            }
            SpanLabel label = new SpanLabel();
            label.setText(message);
            chatContainer.addComponent(label);
            chatContainer.animateHierarchy(100);
          }

        });
      }

      @Override
      protected void onError(Exception ex) {
        System.out.println("in onError");
      }

      @Override
      protected void onMessage(byte[] message) {

      }

    };
    System.out.println("Sending connect");
    sock.connect();
  }

  void showLogin() {
    Form f = new Form("Login");
    f.addComponent(new Label("Name: "));
    final TextField nameField = new TextField();
    f.addComponent(nameField);
    f.addComponent(new Button(new Command("Login") {

      @Override
      public void actionPerformed(ActionEvent evt) {
        sock.send(nameField.getText());
        showChat();
      }

    }));
    f.show();
  }

  void showChat() {
    Form f = new Form("Chat");
    f.setLayout(new BorderLayout());

    Container south = new Container();
    final TextField tf = new TextField();
    Button send = new Button(new Command("Send") {

      @Override
      public void actionPerformed(ActionEvent evt) {
        sock.send(tf.getText());
        tf.setText("");
      }

    });

    chatContainer = new Container();
    chatContainer.setLayout(new BoxLayout(BoxLayout.Y_AXIS));

    south.addComponent(tf);
    south.addComponent(send);
    f.addComponent(BorderLayout.SOUTH, south);
    f.addComponent(BorderLayout.CENTER, chatContainer);
    f.setFormBottomPaddingEditingMode(true);
    f.show();

  }

  public void start() {
    showLogin();

  }

  public void stop() {
    current = Display.getInstance().getCurrent();
  }

  public void destroy() {
  }

}`

**Comment by tmancini** [comment]
I am now thinking I messed up my project's native and lib folders.  When I had success I basically started with the of your project and modified it to fit my needs.  I never successfully created a new project from scratch and imported the library.  When I dumped the cn1lib file into the project's lib directory and did refresh libs, I was getting a ClassNotFoundException on the WebSocketNativeImpl class.

**Comment by tmancini** [comment]
Okay so, I was able to get things working using the build.xml file from cn1-websockets-demo and also needed to copy the nbproject directory into my project.  Should both of these steps be necessary?

**Comment by tmancini** [comment]
I was able to get the Simulator to work by replacing the following in the default build.xml file:

```
<mkdir dir="native/javase" />
                        <mkdir dir="native/internal_tmp" />
                        <javac destdir="native/internal_tmp" compiler="modern"
                            source="1.8"
                            target="1.8"
                            bootclasspath="lib/CLDC11.jar"
                                                                classpath="lib/CodenameOne.jar:${build.classes.dir}:lib/impl/cls:build/tmp">
                            <src path="native/javase"/>
                        </javac>  
```

With this:

```
<mkdir dir="native/javase" />
                <mkdir dir="native/internal_tmp" />
                <mkdir dir="lib/impl/native/javase" />
                <javac destdir="native/internal_tmp"
                source="1.8"
                target="1.8"
                bootclasspath="CLDC11.jar" excludes="${excludes}"
                                                                classpath="lib/CodenameOne.jar:${build.classes.dir}:lib/impl/cls:build/tmp">
                <src path="native/javase"/>
                <src path="lib/impl/native/javase"/>
                </javac>                     
```
